### ISSUE TITLE
Backend server dosent returns an error in API, after user deletes and requests himself. Backend error is not catched

### ISSUE THREAD

**Issue by ProgramPhoenix** [loernwerk/loernwerk#19]
How to reproduce:

1. login
2. move to localhost:5173/account
3. delete Account
4. reload website

Backenderror:
>[dev:backend] ...\loernwerk\backend\controller\AccountController.ts:103
>[dev:backend]             throw new LoernwerkError(
>[dev:backend]                   ^
>[dev:backend] LoernwerkError: No existing User with given ID
>[dev:backend]     at Function.getAccountById (C:\Users\david\Desktop\loernwerk\backend\controlle\AccountController.ts:103:19)
>[dev:backend]     at async C:\Users\david\Desktop\loernwerk\backend\router\AccountRouterFactory.ts:110:26 {
>[dev:backend]   code: 'NOT_FOUND'
>[dev:backend] }
>[dev:backend] npm run dev:backend exited with code 1`

this error will not normaly occur in the account view, as long users can not delete themselves. but this error will probably occur in the admin view, after an admin deletes an account. (Depends on implementation)

**Comment by c0derMo** [comment]
This shouldn't ever happen in the regular account view, since a logged in user should always have an account - unless an admin deletes themselves, although we maybe should enforce that thats not possible.

Anyways, we dont even have an endpoint right now for admins to query userdata, we'll have to implement that once we build the admin view - I'll leave this issue open until we get there.

**Comment by ProgramPhoenix** [comment]
i thought a bit of it and it could also happen, when a logged in user is deleted by an admin and goes to the account view. And i guess the other views for a people with accounts could have the same problem
