### ISSUE TITLE
Empty sequnce possible

### ISSUE THREAD

**Issue by Kr0nox** [loernwerk/loernwerk#30]
Empty sequences can be created and only get filled with at least one slide in the edit view. that means if a teacher never saves the sequence an empty sequnce can be shared

**Comment by c0derMo** [comment]
I'd say this isn't a big issue for now, since this shouldnt provoke any errors if I'm correct - the SlideView should just immediately jump to the FinishedView if i'm correct.

For the future though, I'd say that we just deem every code whose sequence has no slides as invalid, e.g. cant be accessed by the frontend.

**Comment by Kr0nox** [comment]
yes that is what happens
