### ISSUE TITLE
Only password repeat set is valid

### ISSUE THREAD

**Issue by Kr0nox** [loernwerk/loernwerk#68]
When editing your own account data, setting only the repat password and leaving the normal on empty is accepted as a valid input

**Comment by c0derMo** [comment]
It's accepted as valid input, but shouldn't actually change the password though, right?
I assume this is because of [AccountDetailsEditContainer.vue#L187](https://github.com/loernwerk/loernwerk/blob/4e6d58d2c60400ea03ded6407ff23a4527985bc8/frontend/src/components/AccountDetailsEditContainer.vue#L187) here, since we only check if password is non-empty, but not the repeat

**Comment by Kr0nox** [comment]
yes. excactly
